project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    toc-depth: 10
    code-fold: show
    smooth-scroll: true
    comments:
      hypothesis: true
    grid: 
      body-width: 900px
theme: minty